alter session set container = ORCLPDB1;
show con_name;

--Табличное пространство для проекта
CREATE TABLESPACE course_project
DATAFILE 'D:\CourseProject\oracle\CourseProject.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 5M
BLOCKSIZE 8192
EXTENT MANAGEMENT LOCAL;








--Создание ролей
CREATE ROLE ADMIN_ROLE;
CREATE ROLE USER_ROLE;
CREATE ROLE DRIVER_ROLE;


--АДИМИНИСТРАТОР
GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE VIEW,
    CREATE PROCEDURE,
    CREATE PROFILE,
    CREATE USER,
    DROP USER,
    CREATE ROLE,
    DROP PROFILE,
    CREATE TRIGGER,
    DROP ANY TRIGGER,
    CREATE ANY INDEX,
    CREATE TYPE,
    DROP ANY TYPE,
    EXECUTE ANY INDEXTYPE,
    CREATE ANY SEQUENCE
    TO ADMIN_ROLE WITH ADMIN OPTION;

CREATE PROFILE ADMIN_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180 --срок жизни пароля(дни)
    SESSIONS_PER_USER 10 --максимальное количесвто сессий
    FAILED_LOGIN_ATTEMPTS 3 --неудачных попыток входа до блокировки
    PASSWORD_LOCK_TIME 3 --блокировка (дни)
    PASSWORD_REUSE_TIME 10 --повторное использование пароля(дни)
    PASSWORD_GRACE_TIME DEFAULT --использование пароля после истечения срока дейтсвия
    CONNECT_TIME 180 --время подключения пользователя (сессия, минуты)
    IDLE_TIME 30; --максимальное время бездействия
    
--Создание
CREATE USER ADMINCP IDENTIFIED BY admin1234;
--Назначение админу профиля безопасности
ALTER USER ADMINCP PROFILE ADMIN_PROFILE;
--Права на табличное пространство
ALTER USER ADMINCP DEFAULT TABLESPACE course_project QUOTA UNLIMITED ON course_project;
--Назначение админу роли
GRANT ADMIN_ROLE TO ADMINCP;

-- Создаем объект каталога в базе, указываем реальный путь на сервере
CREATE OR REPLACE DIRECTORY JSON_DIR AS '/opt/oracle/oradata';

--  Даем права пользователю ADMINCP на чтение и запись
GRANT READ, WRITE ON DIRECTORY JSON_DIR TO ADMINCP;


--Шифрование пароля (под sys)
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ADMINCP;







--ВОДИТЛЕЬ
--Права
GRANT CREATE SESSION TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.REGISTER_DRIVER TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.SET_VEHICLE_STATUS TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.ADD_BOOKING TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.DELETE_BOOKING TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.GET_TRAVELS_BY_DRIVER TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.UPDATE_BOOKING_STATUS TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.GET_USERS_BY_TRAVEL TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.ADD_STATISTIC TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.GET_USER_BOOKINGS TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.GET_HISTORY_USER_BOOKINGS TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.SORT_TRAVELS_BY_DATE_ROUTE TO DRIVER_ROLE;
GRANT EXECUTE ON ADMINCP.ADD_STATISTIC TO DRIVER_ROLE;

--Профиль безопасности
CREATE PROFILE DRIVER_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 3
    PASSWORD_REUSE_TIME 10
    CONNECT_TIME 180
    IDLE_TIME 60;

--Создание
CREATE USER DRIVERCP IDENTIFIED BY driver1234;
--Назначение водителю профиля безопасности
ALTER USER DRIVERCP PROFILE DRIVER_PROFILE;
--ALTER USER DRIVERCP DEFAULT TABLESPACE course_project QUOTA UNLIMITED ON course_project;
--Назначение водителю роли
GRANT DRIVER_ROLE TO DRIVERCP;



--ПОЛЬЗОВАТЕЛЬ
GRANT CREATE SESSION TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.REGISTER_USER TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.UPDATE_USER TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.ADD_BOOKING TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.DELETE_BOOKING TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.GET_USER_BOOKINGS TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.GET_HISTORY_USER_BOOKINGS TO USER_ROLE;
GRANT EXECUTE ON ADMINCP.SORT_TRAVELS_BY_DATE_ROUTE TO USER_ROLE;

CREATE PROFILE USER_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LOCK_TIME 3
    PASSWORD_REUSE_TIME 10
    CONNECT_TIME 180
    IDLE_TIME 60;
    
--Создание
CREATE USER USERCP IDENTIFIED BY user1234;
--Назначение пользователю профиля безопасности
ALTER USER USERCP PROFILE USER_PROFILE;
--ALTER USER USERCP DEFAULT TABLESPACE course_project QUOTA UNLIMITED ON course_project;
--Назначение пользователю роли
GRANT USER_ROLE TO USERCP;


--УДАЛЕНИЕ
DROP TABLESPACE course_project INCLUDING CONTENTS AND DATAFILES;
DROP PROFILE ADMIN_PROFILE;






